### ISSUE TITLE
Does not connect back

### ISSUE THREAD

**Issue by Chomikmarkus** [MythicAgents/tetanus#2]
Hello!

Have issue after executing it in target machine, it does nothing, no connection back to c2! Target machine windows 2012 R2 server! I can see from process explorer that tetanus.exe starts but after some seconds it stops! 
Http is configured with ssl! 
Have no idea from where to start troubleshooting it, tried reinstall agent issue persist!
Thanks

**Comment by t94j0** [comment]
Try starting the executable from a powershell window to view stdout. If you get "connection refused," then you need to make sure your Windows machine can connect to your C2. If you get a different error, make another issue with exactly what you tried, the way your computers are connected, troubleshooting steps you've already tried, and the exact error message you received.
