### ISSUE TITLE
tetanus connects not back

### ISSUE THREAD

**Issue by Chomikmarkus** [MythicAgents/tetanus#3]
Installed working environment, installed tetanus as every other agent in Mythic!
testing on windows 20212 R2 server, running with powershell getting this error:

PS C:\Users\Administrator\Downloads> ./tetanus.exe
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Custom { kind: InvalidData, error: Inval
idCertificateData("invalid peer certificate: CaUsedAsEndEntity") })', src/profiles/mod.rs:117:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
PS C:\Users\Administrator\Downloads>
i am.running http profile through ssl, with selfsigned certificates!

**Comment by MEhrn00** [comment]
The agent won't accept self-signed SSL certificates. Set up Mythic with a signed cert or use the regular HTTP profile.

**Comment by Chomikmarkus** [comment]
ok thanks
